#!/bin/sh

# Run this script in the S9 root to rebuild the help symlinks

cd help || exit 1

cp="ln -sf"

$cp amb amb-collector
$cp amb amb-donep
$cp amb amb-reset
$cp assq assoc
$cp assq assv
$cp bit0 bitstar
$cp bit0 bitstarc
$cp bit0 bita
$cp bit0 bitcstar
$cp bit0 bitb
$cp bit0 bitneq
$cp bit0 bitplus
$cp bit0 bitnplus
$cp bit0 biteq
$cp bit0 bitcb
$cp bit0 bitplusc
$cp bit0 bitca
$cp bit0 bitcplus
$cp bit0 bitnstar
$cp bit0 bit1
$cp bit0 bitsl
$cp bit0 bitsr
$cp bitwise-and bitwise-1
$cp bitwise-and bitwise-2
$cp bitwise-and bitwise-and-c1
$cp bitwise-and bitwise-and-c2
$cp bitwise-and bitwise-and-not
$cp bitwise-and bitwise-c1
$cp bitwise-and bitwise-c2
$cp bitwise-and bitwise-clear
$cp bitwise-and bitwise-or
$cp bitwise-and bitwise-or-c1
$cp bitwise-and bitwise-or-c2
$cp bitwise-and bitwise-or-not
$cp bitwise-and bitwise-set
$cp bitwise-and bitwise-shift-left
$cp bitwise-and bitwise-shift-right
$cp bitwise-and bitwise-xor
$cp bitwise-and bitwise-xor-not
$cp caar caaaar
$cp caar caaadr
$cp caar caaar
$cp caar caadar
$cp caar caaddr
$cp caar caadr
$cp caar cadaar
$cp caar cadadr
$cp caar cadar
$cp caar caddar
$cp caar cadddr
$cp caar caddr
$cp caar cadr
$cp caar cdaaar
$cp caar cdaadr
$cp caar cdaar
$cp caar cdadar
$cp caar cdaddr
$cp caar cdadr
$cp caar cdar
$cp caar cddaar
$cp caar cddadr
$cp caar cddar
$cp caar cdddar
$cp caar cddddr
$cp caar cdddr
$cp caar cddr
$cp call-with-current-continuation callslashcc
$cp call-with-input-file call-with-output-file
$cp catch throw
$cp char-alphabeticp char-lower-casep
$cp char-alphabeticp char-numericp
$cp char-alphabeticp char-upper-casep
$cp char-alphabeticp char-whitespacep
$cp char-cieqp char-cigep
$cp char-cieqp char-cigtp
$cp char-cieqp char-cilep
$cp char-cieqp char-ciltp
$cp char-to-integer integer-to-char
$cp char-upcase char-downcase
$cp chareqp chargep
$cp chareqp chargtp
$cp chareqp charlep
$cp chareqp charltp
$cp close-input-port close-output-port
$cp combine combinestar
$cp complement compose
$cp complement const
$cp complement curry
$cp complement curryr
$cp complement fork
$cp current-input-port current-output-port
(cd csv; $cp csv_read csv_write)
(cd curses; $cp curs_addch curs_addstr)
(cd curses; $cp curs_addch curs_beep)
(cd curses; $cp curs_addch curs_flash)
(cd curses; $cp curs_addch curs_move)
(cd curses; $cp curs_addch curs_mvaddch)
(cd curses; $cp curs_addch curs_mvaddstr)
(cd curses; $cp curs_addch curs_refresh)
(cd curses; $cp curs_addch curs_scroll)
(cd curses; $cp curs_attroff curs_attron)
(cd curses; $cp curs_attroff curs_attrset)
(cd curses; $cp curs_attroff curs_standend)
(cd curses; $cp curs_attroff curs_standout)
(cd curses; $cp curs_cbreak curs_clearok)
(cd curses; $cp curs_cbreak curs_echo)
(cd curses; $cp curs_cbreak curs_get-magic-value)
(cd curses; $cp curs_cbreak curs_idlok)
(cd curses; $cp curs_cbreak curs_keypad)
(cd curses; $cp curs_cbreak curs_nl)
(cd curses; $cp curs_cbreak curs_nocbreak)
(cd curses; $cp curs_cbreak curs_nodelay)
(cd curses; $cp curs_cbreak curs_noecho)
(cd curses; $cp curs_cbreak curs_nonl)
(cd curses; $cp curs_cbreak curs_noraw)
(cd curses; $cp curs_cbreak curs_raw)
(cd curses; $cp curs_cbreak curs_resetty)
(cd curses; $cp curs_cbreak curs_savetty)
(cd curses; $cp curs_cbreak curs_scrollok)
(cd curses; $cp curs_clear curs_clrtobot)
(cd curses; $cp curs_clear curs_clrtoeol)
(cd curses; $cp curs_color-set curs_has-colors)
(cd curses; $cp curs_cursoff curs_curson)
(cd curses; $cp curs_cursoff curs_mvcur)
(cd curses; $cp curs_delch curs_deleteln)
(cd curses; $cp curs_delch curs_insch)
(cd curses; $cp curs_delch curs_insertln)
(cd curses; $cp curs_delch curs_mvdelch)
(cd curses; $cp curs_delch curs_mvinsch)
(cd curses; $cp curs_endwin curs_initscr)
(cd curses; $cp curs_flushinp curs_cols)
(cd curses; $cp curs_flushinp curs_getch)
(cd curses; $cp curs_flushinp curs_getyx)
(cd curses; $cp curs_flushinp curs_inch)
(cd curses; $cp curs_flushinp curs_lines)
(cd curses; $cp curs_flushinp curs_mvgetch)
(cd curses; $cp curs_flushinp curs_mvinch)
(cd curses; $cp curs_flushinp curs_unctrl)
(cd curses; $cp curs_flushinp curs_ungetch)
$cp define-class call-next-method
$cp define-class class-of
$cp define-class classp
$cp define-class define-generic
$cp define-class define-method
$cp define-class initialize
$cp define-class instancep
$cp define-class make-instance
$cp define-class slot-ref
$cp define-class slot-setb
$cp define-matcher let-matcher
$cp define-matcher make-matcher
$cp draw-tree dt
$cp duplicates dupp
$cp duplicates dupq
$cp duplicates dupv
$cp eq ge
$cp eq gt
$cp eq le
$cp eq lt
$cp exact-to-inexact inexact-to-exact
$cp exactp inexactp
$cp exp log
$cp exp sin
$cp exp cos
$cp exp tan
$cp exp asin
$cp exp acos
$cp exp atan
$cp exponent mantissa
$cp floor ceiling
$cp floor round
$cp floor truncate
$cp force delay
$cp gcd lcm
$cp get-prop put-prop
$cp get-prop rem-prop
$cp get-prop put-propb
$cp get-prop rem-propb
$cp help apropos
$cp htmlify-char htmlify-string
$cp id false
$cp id true
$cp input-portp output-portp
$cp integer-to-binary-string binary-string-to-integer
$cp integer-to-binary-string number-of-bits
$cp iota iotastar
$cp keyword-value accept-keywords
$cp loutify-char loutify-string
$cp macro-expand macro-expand-1
$cp make-array array
$cp make-array arrayp
$cp make-array array-dimensions
$cp make-array array-map
$cp make-array array-rank
$cp make-array array-ref
$cp make-array array-setb
$cp make-array subarray
$cp make-canvas canvas-draw
$cp make-canvas canvas-draw-string
$cp make-canvas canvas-dump
$cp make-canvas canvas-plot
$cp make-canvas canvas-plot-line
$cp make-hash-table alist-to-hash-table
$cp make-hash-table hash-table-length
$cp make-hash-table hash-table-ref
$cp make-hash-table hash-table-removeb
$cp make-hash-table hash-table-setb
$cp make-hash-table hash-table-to-alist
$cp make-rbt rbt-find
$cp make-rbt rbt-insert
$cp make-rbt rbt-rebuild
$cp make-rbt rbt-remove
$cp make-stream append-streams
$cp make-stream filter-stream
$cp make-stream list-to-stream
$cp make-stream map-stream
$cp make-stream stream-any
$cp make-stream stream-eosp
$cp make-stream stream-extract
$cp make-stream stream-id
$cp make-stream stream-iota
$cp make-stream stream-member
$cp make-stream stream-next
$cp make-stream stream-none
$cp make-stream stream-to-list
$cp make-stream stream-value
$cp max min
$cp memoize define-memoizing
$cp memq member
$cp memq memv
$cp minus slash
$cp module using
$cp numberp integerp
$cp numberp realp
(cd sys-unix; $cp parse-optionsb display-usage)
(cd sys-unix; $cp parse-optionsb opt-argp)
(cd sys-unix; $cp parse-optionsb opt-char)
(cd sys-unix; $cp parse-optionsb opt-type)
(cd sys-unix; $cp parse-optionsb opt-val)
(cd sys-unix; $cp parse-optionsb option)
$cp permute permutestar
$cp plus star
$cp position posp
$cp position posv
$cp position posq
$cp pretty-print pp
$cp pretty-print pp-file
$cp pretty-print pp-loop
$cp pretty-print pp-string
$cp prolog factb
$cp prolog new-databaseb
$cp prolog predicateb
$cp prolog query
$cp pushb decb
$cp pushb incb
$cp pushb popb
$cp pushb set-varsb
$cp pushb swapb
$cp quasiquote unquote
$cp quasiquote unquote-splicing
$cp queue make-queue
$cp queue queue-emptyp
$cp queue queueb
$cp queue unqueueb
$cp queue unqueuestar
$cp quotient modulo
$cp quotient remainder
$cp r4rs-procedures r4rs-syntax-objects
$cp r4rs-procedures s9fes-syntax-objects
$cp r4rs-procedures s9fes-procedures
$cp r4rs-procedures s9fes-extension-procedures
$cp r4rs-procedures s9fes-extension-symbols
$cp random random-state
$cp re-comp re-match
$cp re-comp re-subst
$cp record assert-record-type
$cp record list-to-record
$cp record record-copy
$cp record record-equalp
$cp record record-ref
$cp record record-setb
$cp record record-signature
$cp record record-to-list
$cp record record-type-matches
$cp record recordp
$cp remove remp
$cp remove remq
$cp remove remv
$cp set-input-portb set-output-portb
(cd sys-unix; $cp spawn-command spawn-command_fd)
(cd sys-unix; $cp spawn-shell-command spawn-shell-command_fd)
$cp split-url url-anchor
$cp split-url url-args
$cp split-url url-host
$cp split-url url-path
$cp split-url url-proto
$cp split-url url-suffix
(cd sys-unix; $cp standard-error-port call-with-stderr)
(cd sys-unix; $cp standard-error-port with-output-to-stderr)
$cp starstar starepsilonstar
$cp starstar starextensionsstar
$cp starstar starhost-systemstar
$cp starstar starlibrary-pathstar
$cp starstar starloadingstar
$cp string-find string-ci-find
$cp string-find string-ci-find-word
$cp string-find string-find-word
$cp string-find-last string-ci-find-last
$cp string-find-last string-ci-find-last-word
$cp string-find-last string-find-last-word
$cp string-last-position string-ci-last-position
$cp string-last-position string-ci-last-word-position
$cp string-last-position string-last-word-position
$cp string-locate string-ci-locate
$cp string-map string-mapb
$cp string-position string-ci-position
$cp string-position string-ci-word-position
$cp string-position string-word-position
$cp string-prefixeqp string-prefix-cieqp
$cp string-scan string-ci-scan
$cp string-to-list list-to-string
$cp string-upcase string-downcase
$cp stringeqp string-cieqp
$cp stringltp string-cigep
$cp stringltp string-cigtp
$cp stringltp string-cilep
$cp stringltp string-ciltp
$cp stringltp stringgep
$cp stringltp stringgtp
$cp stringltp stringlep
(cd sys-unix; $cp sys_chmod sys_change_mode)
(cd sys-unix; $cp sys_dup sys_dup2)
(cd sys-unix; $cp sys_getgrnam sys_getgrgid)
(cd sys-unix; $cp sys_getpgid sys_setpgid)
(cd sys-unix; $cp sys_getpwnam sys_getpwuid)
(cd sys-unix; $cp sys_getuid sys_getgid)
(cd sys-unix; $cp sys_group-name sys_group-gid)
(cd sys-unix; $cp sys_inet-listen sys_inet-accept)
(cd sys-unix; $cp sys_kill sys_notify)
(cd sys-unix; $cp sys_make-input-port sys_make-output-port)
(cd sys-unix; $cp sys_open sys_close)
(cd sys-unix; $cp sys_open sys_creat)
(cd sys-unix; $cp sys_read sys_write)
(cd sys-unix; $cp sys_setuid sys_setgid)
(cd sys-unix; $cp sys_stat sys_lstat)
(cd sys-unix; $cp sys_stat-name sys_lstat-atime)
(cd sys-unix; $cp sys_stat-name sys_lstat-ctime)
(cd sys-unix; $cp sys_stat-name sys_lstat-dev)
(cd sys-unix; $cp sys_stat-name sys_lstat-gid)
(cd sys-unix; $cp sys_stat-name sys_lstat-ino)
(cd sys-unix; $cp sys_stat-name sys_lstat-mode)
(cd sys-unix; $cp sys_stat-name sys_lstat-mtime)
(cd sys-unix; $cp sys_stat-name sys_lstat-name)
(cd sys-unix; $cp sys_stat-name sys_lstat-nlink)
(cd sys-unix; $cp sys_stat-name sys_lstat-size)
(cd sys-unix; $cp sys_stat-name sys_lstat-uid)
(cd sys-unix; $cp sys_stat-name sys_stat-atime)
(cd sys-unix; $cp sys_stat-name sys_stat-ctime)
(cd sys-unix; $cp sys_stat-name sys_stat-dev)
(cd sys-unix; $cp sys_stat-name sys_stat-gid)
(cd sys-unix; $cp sys_stat-name sys_stat-ino)
(cd sys-unix; $cp sys_stat-name sys_stat-mode)
(cd sys-unix; $cp sys_stat-name sys_stat-mtime)
(cd sys-unix; $cp sys_stat-name sys_stat-nlink)
(cd sys-unix; $cp sys_stat-name sys_stat-size)
(cd sys-unix; $cp sys_stat-name sys_stat-uid)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-block-devp)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-char-devp)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-directoryp)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-pipep)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-regularp)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-socketp)
(cd sys-unix; $cp sys_stat-regularp sys_lstat-symlinkp)
(cd sys-unix; $cp sys_stat-regularp sys_stat-block-devp)
(cd sys-unix; $cp sys_stat-regularp sys_stat-char-devp)
(cd sys-unix; $cp sys_stat-regularp sys_stat-directoryp)
(cd sys-unix; $cp sys_stat-regularp sys_stat-pipep)
(cd sys-unix; $cp sys_stat-regularp sys_stat-socketp)
(cd sys-unix; $cp sys_user-name sys_user-gecos)
(cd sys-unix; $cp sys_user-name sys_user-gid)
(cd sys-unix; $cp sys_user-name sys_user-home)
(cd sys-unix; $cp sys_user-name sys_user-shell)
(cd sys-unix; $cp sys_user-name sys_user-uid)
(cd sys-unix; $cp sys_usleep sys_sleep)
(cd sys-unix; $cp sys_wait sys_waitpid)
$cp t-sort t-sort-net
$cp tagbody go
$cp thread-create thread-exit
$cp thread-create thread-start
$cp thread-create thread-yield
$cp time-add time-subtract
$cp time-add time-difference
$cp time-add time-beforep
$cp time-add time-afterp
(cd sys-unix; $cp time timestar)
$cp type-case type-of
$cp vector-to-list list-to-vector
$cp vector-map vector-mapb
$cp when unless
$cp while until
$cp with-input-from-file with-output-to-file
$cp write-to-string display-to-string
$cp zerop evenp
$cp zerop negativep
$cp zerop oddp
$cp zerop positivep
